# Generated by Django 3.2.6 on 2021-09-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_last_checked_tender'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCheckedTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_tender', models.CharField(max_length=1000)),
                ('tender', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Last_checked_tender',
        ),
    ]
